#!/bin/sh

image=ClientApp
version=1.0

mvn clean package

./buildx-bootstrap

docker buildx build --platform=linux/amd64,linux/arm64/v8 --push -t ivonet/"${image}":latest .
docker buildx build --platform=linux/amd64,linux/arm64/v8 --push -t ivonet/"${image}":"${version}" .
docker pull ivonet/archetypetest:latest
